# Generated by Django 4.2.5 on 2023-12-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_comment_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='imageURL',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
